version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/postgres:/migrations

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./migrations/postgres:/migrations
    command: [ "-path=/migrations", "-database=postgres://myuser:mypassword@db:5432/postgres?sslmode=disable", "up" ]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "50051:50051"
    environment:
      DATABASE_URL: postgres://myuser:mypassword@db:5432/postgres?sslmode=disable

volumes:
  postgres_data: